---
driver:
  name: vagrant   # NOTE: the roles run by this Kitchen setup require starting Docker containers. To migrate this driver to "docker" requires a solution to run docker-in-docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  requirements_path: requirements.yml
  require_pip: true
  require_ansible_repo: false
  ansible_version:  2.5.6.0
  ansible_verbose:  false
  ansible_verbosity: 2
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ignore_paths_from_root:
    - .kitchen
  ssh_known_hosts:
    - github.com

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64
  - name: ubuntu-16.04
    driver:
      box: ubuntu/xenial64
  - name: centos-7.2
    driver:
      box: bento/centos-7.2

suites:
  - name: default
    driver:
      network:
        - ["private_network", { ip: "172.9.1.1" }]

transport:
  max_ssh_sessions: 4
  forward_agent: true
