---
- name: Start firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Check firewalld configuration
  shell: firewall-cmd --list-ports
  register: firewall_result

- name: Configure firewalld 80 tcp
  firewalld:
    port: 80/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "'80/tcp' not in firewall_result.stdout"
